### ISSUE TITLE
TypeError: dest.write is not a function

### ISSUE THREAD

**Issue by MegaUITeam** [sindresorhus/gulp-filter#82]
5+ version has error, 4.0.0 version no error

my gulpfile
```coffeescript
compileStream = (stream, dest)->
	filterCoffee = filter('**/*.coffee', {restore: true, passthrough: false})

	return stream
		.pipe(filterCoffee)
		.pipe(coffeescript())
		.pipe(filterCoffee.restore)
		.pipe(gulp.dest(dest))
```

`.pipe(filterCoffee.restore)` and `passthrough: false` throws this error

console log:
```sh
[03:24:09] Starting 'buildServer'...
[03:24:09] 'buildServer' errored after 116 ms
[03:24:09] TypeError: dest.write is not a function
    at write (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at emitReadable_ (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.transform [as _transform] (C:\localhost\donation-physics\node_modules\gulp-coffeescript\index.js:50:3)
    at DestroyableTransform.Transform._read (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\localhost\donation-physics\node_modules\gulp-coffeescript\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at StreamFilter.ondata (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:541:20)
    at emitOne (events.js:115:13)
    at StreamFilter.emit (events.js:210:7)
    at readableAddChunk (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:212:18)
    at StreamFilter.Readable.push (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:171:10)
    at StreamFilter.Transform.push (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at StreamFilterCallback (C:\localhost\donation-physics\node_modules\streamfilter\src\index.js:30:15)
    at streamfilter (C:\localhost\donation-physics\node_modules\gulp-filter\index.js:33:3)
    at StreamFilter.streamFilterTransform [as _transform] (C:\localhost\donation-physics\node_modules\streamfilter\src\index.js:28:5)
    at StreamFilter.Transform._read (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at StreamFilter.Transform._write (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_writable.js:338:64)
    at writeOrBuffer (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_writable.js:327:5)
    at StreamFilter.Writable.write (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_writable.js:264:11)
    at DestroyableTransform.ondata (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:541:20)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)
    at readableAddChunk (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:212:18)
    at DestroyableTransform.Readable.push (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_readable.js:171:10)
    at DestroyableTransform.Transform.push (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at afterTransform (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:79:51)
    at TransformState.afterTransform (C:\localhost\donation-physics\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at C:\localhost\donation-physics\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:18:5
    at C:\localhost\donation-physics\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)

[03:24:09] 'build' errored after 234 ms

Process finished with exit code 1
```

**Comment by kevva** [comment]
That's because using `passthrough: false` will return the files as a readable stream which doesn't have a `write` method. Can you try without it?
