### ISSUE TITLE
TypeError: dest.end is not a function [Used with event-stream]

### ISSUE THREAD

**Issue by ulivz** [sindresorhus/gulp-filter#83]
## ENV

- mac 10.12.5
- Node 6.11.2

## description
When I wrote like this:

```
gulp.task('SVG', () => {
			return es.merge(locales.map((locale) => {

				let cssFilter = filter('*.css', {restore: true, passthrough: false});
				return gulp.src(`public/svgsV2/${locale}/*.svg`)
					.pipe(svgmin())
					.pipe(svgcss())
					.pipe(cssFilter)
					.pipe(cssmin())
					.pipe(cssFilter.restore)
					.pipe(gulp.dest(`./public/css/${locale}`));
			}));
		});
```

Which throws error as follows:

```
internal/streams/legacy.js:44
    dest.end();
         ^

TypeError: dest.end is not a function
    at Stream.onend (internal/streams/legacy.js:44:10)
    at emitNone (events.js:91:20)
    at Stream.emit (events.js:185:7)
    at end (/Users/haolchen/Documents/__eBay__/bolt-2dot0-frontend/node_modules/gulp-cssmin/node_modules/map-stream/index.js:108:39)
    at queueData (/Users/haolchen/Documents/__eBay__/bolt-2dot0-frontend/node_modules/gulp-cssmin/node_modules/map-stream/index.js:57:17)
    at next (/Users/haolchen/Documents/__eBay__/bolt-2dot0-frontend/node_modules/gulp-cssmin/node_modules/map-stream/index.js:68:5)
    at /Users/haolchen/Documents/__eBay__/bolt-2dot0-frontend/node_modules/gulp-cssmin/node_modules/map-stream/index.js:77:7
    at /Users/haolchen/Documents/__eBay__/bolt-2dot0-frontend/node_modules/gulp-cssmin/index.js:47:6
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

**Comment by nfroidure** [comment]
`passthrough` is set to false so your stream is not writable.
